# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writers' Organizations
email: david@davidlday.com
description: > # this means to ignore newlines until "baseurl:"
  A directory of US nonprofit professional organizations for writers of fiction prose and poetry.
<<<<<<< HEAD
baseurl: "/writers-organizations" # the subpath of your site, e.g. /blog
url: "http://davidlday.github.io" # the base hostname & protocol for your site
=======
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
>>>>>>> fc8d2307d58f60889c8916143d2227bee9a8221b
twitter_username: dday376
github_username:  davidlday

# Build settings
markdown: kramdown
timezone: America/New_York

# Links to public resources
nccs_url: http://nccsweb.urban.org/communityplatform/nccs/organization/profile/id/
propublica_url: https://projects.propublica.org/nonprofits/organizations/
guidestar_url: http://www.guidestar.org/profile/
