# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Writers' Organizations
email: david@davidlday.com
description: > # this means to ignore newlines until "baseurl:"
  A directory of US nonprofit professional organizations for writers of fiction prose and poetry.
baseurl: "/writers-organizations" # the subpath of your site, e.g. /blog
url: "http://davidlday.github.io" # the base hostname & protocol for your site
twitter_username: dday376
github_username:  davidlday

# Build settings
markdown: kramdown
timezone: America/New_York

# Links to public resources
nccs_url: http://nccsweb.urban.org/communityplatform/nccs/organization/profile/id/
propublica_url: https://projects.propublica.org/nonprofits/organizations/
guidestar_url: http://www.guidestar.org/profile/
irs_extracts: https://www.irs.gov/uac/SOI-Tax-Stats-Annual-Extract-of-Tax-Exempt-Organization-Financial-Data
